### ISSUE TITLE
Keep JACK Outputs Opened All the Time

### ISSUE THREAD

**Issue by NexAdn** [TheWiseNoob/OMP#5]
I'd like to use OMP with JACK and connect it to ports other than the hardware playback ports which OMP connects to by default, but everytime a new track is played back, the OMP ports reconnect to the hp ports, more specific: The OMP ports are closed when the music stops and reopened when the music starts. To use OMP in the way I need it, I would have to delete an reconnect all OMP ports manually everytime when a new track is played back. 

It would be much better to have OMP open it's JACK ports on startup and closing them on shutdown.

**Comment by TheWiseNoob** [comment]
Hmmm, okay. That's an interesting issue. I only tested ALSA and PulseAudio. I didn't test JACK output. I just added it as an output option, but I will definitely look into this problem as soon as I can.

**Comment by NexAdn** [comment]
Any progress?

**Comment by TheWiseNoob** [comment]
Yes. It's because [this value](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-jackaudiosink.html#GstJackAudioSink--connect) of the GStreamer element for JACK output is by default set to switch to physical ports. I just need to provide a configuration option to change it. I plan to before the release of the first code-stable build. I need to research JACK more and use it myself because I don't understand how it works and I have never used it. I provided the initial JACK support more as an untested proof-of-concept.
